### ISSUE TITLE
Perus sovelluspohjan luonti

### ISSUE THREAD

**Issue by leftidev** [jantsavlog/JKLnyt_GIT#4]
Luodaan sovelluspohja (skeleton). Sovelluksen "Hello World", tarkoituksena on saada ensimmäinen testijulkaisu vain kauppaan.

**Comment by leftidev** [comment]
Testijulkaisua varten:

- yhden tiimistä täytyy hankkia Google Developer tili, jonka kautta voidaan sovellus julkaista kauppaan

**Comment by jantsavlog** [comment]
Sovelluspohja on luotu onnistuneesti:)
